//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSIV
    {
        public int ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string LIG { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public Nullable<int> IDDAA_ID { get; set; }
        public Nullable<int> BETRADAR_ID { get; set; }
        public Nullable<int> UZAKLIK { get; set; }
        public Nullable<int> MBS { get; set; }
        public string SKOR_IY { get; set; }
        public string SKOR_MS { get; set; }
        public Nullable<decimal> MS_1 { get; set; }
        public Nullable<decimal> MS_X { get; set; }
        public Nullable<decimal> MS_2 { get; set; }
        public Nullable<decimal> IY_1 { get; set; }
        public Nullable<decimal> IY_X { get; set; }
        public Nullable<decimal> IY_2 { get; set; }
        public Nullable<decimal> H_1 { get; set; }
        public Nullable<decimal> H_X { get; set; }
        public Nullable<decimal> H_2 { get; set; }
        public Nullable<decimal> KGV { get; set; }
        public Nullable<decimal> KGY { get; set; }
        public Nullable<decimal> CIFT_1_X { get; set; }
        public Nullable<decimal> CIFT_1_2 { get; set; }
        public Nullable<decimal> CIFT_2_X { get; set; }
        public Nullable<decimal> ALT_IY { get; set; }
        public Nullable<decimal> UST_IY { get; set; }
        public Nullable<decimal> ALT_1_5 { get; set; }
        public Nullable<decimal> UST_1_5 { get; set; }
        public Nullable<decimal> ALT_2_5 { get; set; }
        public Nullable<decimal> UST_2_5 { get; set; }
        public Nullable<decimal> ALT_3_5 { get; set; }
        public Nullable<decimal> UST_3_5 { get; set; }
        public Nullable<decimal> TG_0_1 { get; set; }
        public Nullable<decimal> TG_2_3 { get; set; }
        public Nullable<decimal> TG_4_6 { get; set; }
        public Nullable<decimal> TG_7_ARTI { get; set; }
    }
}
