//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTRIBUTE_MIN_MAX_DEGER
    {
        public int ID { get; set; }
        public string ATTRIBUTE { get; set; }
        public Nullable<decimal> MIN { get; set; }
        public Nullable<decimal> MAX { get; set; }
    }
}
