//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKMAKER_ODD
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<decimal> MS_1 { get; set; }
        public Nullable<decimal> MS_X { get; set; }
        public Nullable<decimal> MS_2 { get; set; }
        public Nullable<decimal> ALT_2_5 { get; set; }
        public Nullable<decimal> UST_2_5 { get; set; }
        public Nullable<int> BETRADAR_ID { get; set; }
        public Nullable<decimal> MS_1_IDDAA { get; set; }
        public Nullable<decimal> MS_X_IDDAA { get; set; }
        public Nullable<decimal> MS_2_IDDAA { get; set; }
        public Nullable<decimal> ALT_2_5_IDDAA { get; set; }
        public Nullable<decimal> UST_2_5_IDDAA { get; set; }
    }
}
