//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANLI_ISTATISTIK
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public int BETRADAR_ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public int DAKIKA { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public string SKOR { get; set; }
        public string SKOR_IY { get; set; }
        public string SKOR_MS { get; set; }
        public Nullable<int> TOPA_SAHIP_IY { get; set; }
        public Nullable<int> SARI_KART_IY { get; set; }
        public Nullable<int> KIRMIZI_KART_IY { get; set; }
        public Nullable<int> KORNER_IY { get; set; }
        public Nullable<int> FRIKIK_IY { get; set; }
        public Nullable<int> KALE_VURUS_IY { get; set; }
        public Nullable<int> TAC_IY { get; set; }
        public Nullable<int> OFSAYT_IY { get; set; }
        public Nullable<int> SUT_ISABET_IY { get; set; }
        public Nullable<int> SUT_ISABETSIZ_IY { get; set; }
        public Nullable<int> KURTARIS_IY { get; set; }
        public Nullable<int> FAUL_IY { get; set; }
        public Nullable<int> SUT_BLOK_IY { get; set; }
        public Nullable<int> GOL_DENEME_IY { get; set; }
        public Nullable<int> SAKAT_IY { get; set; }
        public Nullable<int> TOP_GUVENDE_IY { get; set; }
        public Nullable<int> HUCUM_IY { get; set; }
        public Nullable<int> TEHLIKELI_ATAK_IY { get; set; }
        public Nullable<int> TOPA_SAHIP_MS { get; set; }
        public Nullable<int> SARI_KART_MS { get; set; }
        public Nullable<int> KIRMIZI_KART_MS { get; set; }
        public Nullable<int> KORNER_MS { get; set; }
        public Nullable<int> FRIKIK_MS { get; set; }
        public Nullable<int> KALE_VURUS_MS { get; set; }
        public Nullable<int> TAC_MS { get; set; }
        public Nullable<int> OFSAYT_MS { get; set; }
        public Nullable<int> SUT_ISABET_MS { get; set; }
        public Nullable<int> SUT_ISABETSIZ_MS { get; set; }
        public Nullable<int> KURTARIS_MS { get; set; }
        public Nullable<int> FAUL_MS { get; set; }
        public Nullable<int> SUT_BLOK_MS { get; set; }
        public Nullable<int> GOL_DENEME_MS { get; set; }
        public Nullable<int> SAKAT_MS { get; set; }
        public Nullable<int> TOP_GUVENDE_MS { get; set; }
        public Nullable<int> HUCUM_MS { get; set; }
        public Nullable<int> TEHLIKELI_ATAK_MS { get; set; }
        public string TIP { get; set; }
    }
}
