//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EV_SAHIBI_SON_MAC
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string LIG { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public string SKOR_IY { get; set; }
        public string SKOR_MS { get; set; }
        public string SONUC { get; set; }
    }
}
