//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILK_YARI_SONU_ISTATISTIK
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public Nullable<int> GENEL_EV_GALIBIYET { get; set; }
        public Nullable<decimal> GENEL_EV_GALIBIYET_ORAN { get; set; }
        public Nullable<int> GENEL_EV_BERABER { get; set; }
        public Nullable<decimal> GENEL_EV_BERABER_ORAN { get; set; }
        public Nullable<int> GENEL_EV_MAGLUBIYET { get; set; }
        public Nullable<decimal> GENEL_EV_MAGLUBIYET_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_GALIBIYET { get; set; }
        public Nullable<decimal> GENEL_DEP_GALIBIYET_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_BERABER { get; set; }
        public Nullable<decimal> GENEL_DEP_BERABER_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_MAGLUBIYET { get; set; }
        public Nullable<decimal> GENEL_DEP_MAGLUBIYET_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_GALIBIYET { get; set; }
        public Nullable<decimal> IC_DIS_EV_GALIBIYET_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_BERABER { get; set; }
        public Nullable<decimal> IC_DIS_EV_BERABER_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_MAGLUBIYET { get; set; }
        public Nullable<decimal> IC_DIS_EV_MAGLUBIYET_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_GALIBIYET { get; set; }
        public Nullable<decimal> IC_DIS_DEP_GALIBIYET_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_BERABER { get; set; }
        public Nullable<decimal> IC_DIS_DEP_BERABER_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_MAGLUBIYET { get; set; }
        public Nullable<decimal> IC_DIS_DEP_MAGLUBIYET_ORAN { get; set; }
        public Nullable<int> ARA_EV_GALIBIYET { get; set; }
        public Nullable<decimal> ARA_EV_GALIBIYET_ORAN { get; set; }
        public Nullable<int> ARA_EV_BERABER { get; set; }
        public Nullable<decimal> ARA_EV_BERABER_ORAN { get; set; }
        public Nullable<int> ARA_EV_MAGLUBIYET { get; set; }
        public Nullable<decimal> ARA_EV_MAGLUBIYET_ORAN { get; set; }
        public Nullable<int> ARA_DEP_GALIBIYET { get; set; }
        public Nullable<decimal> ARA_DEP_GALIBIYET_ORAN { get; set; }
        public Nullable<int> ARA_DEP_BERABER { get; set; }
        public Nullable<decimal> ARA_DEP_BERABER_ORAN { get; set; }
        public Nullable<int> ARA_DEP_MAGLUBIYET { get; set; }
        public Nullable<decimal> ARA_DEP_MAGLUBIYET_ORAN { get; set; }
    }
}
