//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class KG_VAR_YOK_ISTATISTIK
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public Nullable<int> GENEL_EV_KGV { get; set; }
        public Nullable<decimal> GENEL_EV_KGV_ORAN { get; set; }
        public Nullable<int> GENEL_EV_KGY { get; set; }
        public Nullable<decimal> GENEL_EV_KGY_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_KGV { get; set; }
        public Nullable<decimal> IC_DIS_EV_KGV_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_KGY { get; set; }
        public Nullable<decimal> IC_DIS_EV_KGY_ORAN { get; set; }
        public Nullable<int> ARA_EV_KGV { get; set; }
        public Nullable<decimal> ARA_EV_KGV_ORAN { get; set; }
        public Nullable<int> ARA_EV_KGY { get; set; }
        public Nullable<decimal> ARA_EV_KGY_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_KGV { get; set; }
        public Nullable<decimal> GENEL_DEP_KGV_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_KGY { get; set; }
        public Nullable<decimal> GENEL_DEP_KGY_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_KGV { get; set; }
        public Nullable<decimal> IC_DIS_DEP_KGV_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_KGY { get; set; }
        public Nullable<decimal> IC_DIS_DEP_KGY_ORAN { get; set; }
        public Nullable<int> ARA_DEP_KGV { get; set; }
        public Nullable<decimal> ARA_DEP_KGV_ORAN { get; set; }
        public Nullable<int> ARA_DEP_KGY { get; set; }
        public Nullable<decimal> ARA_DEP_KGY_ORAN { get; set; }
    }
}
