//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIG_ISLEME
    {
        public int ID { get; set; }
        public int SIRA { get; set; }
        public System.DateTime TARIH { get; set; }
        public string LIG { get; set; }
        public string BASLADI { get; set; }
        public string BITTI { get; set; }
        public string TIP { get; set; }
    }
}
