//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDDAA_Entities : DbContext
    {
        public IDDAA_Entities()
            : base("name=IDDAA_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARALARINDA_SON_MAC> ARALARINDA_SON_MAC { get; set; }
        public virtual DbSet<ARSIV> ARSIV { get; set; }
        public virtual DbSet<ATTRIBUTE_MIN_MAX_DEGER> ATTRIBUTE_MIN_MAX_DEGER { get; set; }
        public virtual DbSet<BOOKMAKER_BULTEN> BOOKMAKER_BULTEN { get; set; }
        public virtual DbSet<BOOKMAKER_ODD> BOOKMAKER_ODD { get; set; }
        public virtual DbSet<BULTEN> BULTEN { get; set; }
        public virtual DbSet<CANLI_ISTATISTIK> CANLI_ISTATISTIK { get; set; }
        public virtual DbSet<DEPLASMAN_SON_MAC> DEPLASMAN_SON_MAC { get; set; }
        public virtual DbSet<EV_SAHIBI_SON_MAC> EV_SAHIBI_SON_MAC { get; set; }
        public virtual DbSet<ILK_YARI_SONU_ISTATISTIK> ILK_YARI_SONU_ISTATISTIK { get; set; }
        public virtual DbSet<KG_VAR_YOK_ISTATISTIK> KG_VAR_YOK_ISTATISTIK { get; set; }
        public virtual DbSet<MAC_SONU_ISTATISTIK> MAC_SONU_ISTATISTIK { get; set; }
        public virtual DbSet<MS25_ALT_UST_ISTATISTIK> MS25_ALT_UST_ISTATISTIK { get; set; }
        public virtual DbSet<OGRENME> OGRENME { get; set; }
        public virtual DbSet<OYUNCU_GOL_SAYISI> OYUNCU_GOL_SAYISI { get; set; }
        public virtual DbSet<PARAMETRE> PARAMETRE { get; set; }
        public virtual DbSet<POPULER_BAHIS> POPULER_BAHIS { get; set; }
        public virtual DbSet<PUAN_DURUMU> PUAN_DURUMU { get; set; }
        public virtual DbSet<SAKAT_CEZALI> SAKAT_CEZALI { get; set; }
        public virtual DbSet<TAKIM_ISTATISTIK> TAKIM_ISTATISTIK { get; set; }
        public virtual DbSet<TOPLAM_GOL_ISTATISTIK> TOPLAM_GOL_ISTATISTIK { get; set; }
        public virtual DbSet<TAHMIN_ML> TAHMIN_ML { get; set; }
        public virtual DbSet<TAHMIN_SONUC> TAHMIN_SONUC { get; set; }
        public virtual DbSet<TAHMIN_TEST> TAHMIN_TEST { get; set; }
        public virtual DbSet<TAHMIN_ML_HEPSI> TAHMIN_ML_HEPSI { get; set; }
        public virtual DbSet<TAHMIN_PROBABILITY> TAHMIN_PROBABILITY { get; set; }
        public virtual DbSet<LIG_ISLEME> LIG_ISLEME { get; set; }
        public virtual DbSet<SINIFLANDIRMA_SONUC> SINIFLANDIRMA_SONUC { get; set; }
        public virtual DbSet<SINIFLANDIRMA_TEST> SINIFLANDIRMA_TEST { get; set; }
    }
}
