//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS25_ALT_UST_ISTATISTIK
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public Nullable<int> GENEL_EV_ALT { get; set; }
        public Nullable<decimal> GENEL_EV_ALT_ORAN { get; set; }
        public Nullable<int> GENEL_EV_UST { get; set; }
        public Nullable<decimal> GENEL_EV_UST_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_ALT { get; set; }
        public Nullable<decimal> IC_DIS_EV_ALT_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_UST { get; set; }
        public Nullable<decimal> IC_DIS_EV_UST_ORAN { get; set; }
        public Nullable<int> ARA_EV_ALT { get; set; }
        public Nullable<decimal> ARA_EV_ALT_ORAN { get; set; }
        public Nullable<int> ARA_EV_UST { get; set; }
        public Nullable<decimal> ARA_EV_UST_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_ALT { get; set; }
        public Nullable<decimal> GENEL_DEP_ALT_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_UST { get; set; }
        public Nullable<decimal> GENEL_DEP_UST_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_ALT { get; set; }
        public Nullable<decimal> IC_DIS_DEP_ALT_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_UST { get; set; }
        public Nullable<decimal> IC_DIS_DEP_UST_ORAN { get; set; }
        public Nullable<int> ARA_DEP_ALT { get; set; }
        public Nullable<decimal> ARA_DEP_ALT_ORAN { get; set; }
        public Nullable<int> ARA_DEP_UST { get; set; }
        public Nullable<decimal> ARA_DEP_UST_ORAN { get; set; }
    }
}
