//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENME
    {
        public int ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public int IDDAA_ID { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public string SONUC { get; set; }
        public string TIPI { get; set; }
        public string SONUC_REAL { get; set; }
        public string LIG { get; set; }

        public OGRENME ShallowCopy()
        {
            return (OGRENME)this.MemberwiseClone();
        }
    }
}
