//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OYUNCU_GOL_SAYISI
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string TAKIM_ADI { get; set; }
        public string OYUNCU_ADI { get; set; }
        public int GOL_SAYISI { get; set; }
    }
}
