//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class POPULER_BAHIS
    {
        public int ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public System.DateTime MAC_TARIH { get; set; }
        public int IDDAA_ID { get; set; }
        public int BETRADAR_ID { get; set; }
        public int OYNANMA_SAYI { get; set; }
        public string TIP { get; set; }
        public string DEGER { get; set; }
        public int MBS { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<int> SIRA { get; set; }
        public Nullable<decimal> MS_1_IDDAA { get; set; }
        public Nullable<decimal> MS_X_IDDAA { get; set; }
        public Nullable<decimal> MS_2_IDDAA { get; set; }
        public Nullable<decimal> ALT_2_5_IDDAA { get; set; }
        public Nullable<decimal> UST_2_5_IDDAA { get; set; }
    }
}
