//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUAN_DURUMU
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string TAKIM_ADI { get; set; }
        public Nullable<int> GENEL_SIRA { get; set; }
        public Nullable<int> GENEL_MAC_SAYISI { get; set; }
        public Nullable<int> GENEL_GALIBIYET { get; set; }
        public Nullable<int> GENEL_BERABERLIK { get; set; }
        public Nullable<int> GENEL_MAGLUBIYET { get; set; }
        public Nullable<int> GENEL_ATTIGI_GOL { get; set; }
        public Nullable<int> GENEL_YEDIGI_GOL { get; set; }
        public Nullable<int> GENEL_PUAN { get; set; }
        public Nullable<int> EV_SAHIBI_SIRA { get; set; }
        public Nullable<int> EV_SAHIBI_MAC_SAYISI { get; set; }
        public Nullable<int> EV_SAHIBI_GALIBIYET { get; set; }
        public Nullable<int> EV_SAHIBI_BERABERLIK { get; set; }
        public Nullable<int> EV_SAHIBI_MAGLUBIYET { get; set; }
        public Nullable<int> EV_SAHIBI_ATTIGI_GOL { get; set; }
        public Nullable<int> EV_SAHIBI_YEDIGI_GOL { get; set; }
        public Nullable<int> EV_SAHIBI_PUAN { get; set; }
        public Nullable<int> DEPLASMAN_SIRA { get; set; }
        public Nullable<int> DEPLASMAN_MAC_SAYISI { get; set; }
        public Nullable<int> DEPLASMAN_GALIBIYET { get; set; }
        public Nullable<int> DEPLASMAN_BERABERLIK { get; set; }
        public Nullable<int> DEPLASMAN_MAGLUBIYET { get; set; }
        public Nullable<int> DEPLASMAN_ATTIGI_GOL { get; set; }
        public Nullable<int> DEPLASMAN_YEDIGI_GOL { get; set; }
        public Nullable<int> DEPLASMAN_PUAN { get; set; }
    }
}
