//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINIFLANDIRMA_TEST
    {
        public int ID { get; set; }
        public string LIG { get; set; }
        public string TIP { get; set; }
        public int ISLENDI { get; set; }
        public Nullable<System.DateTime> BASLAMA_TARIH { get; set; }
        public Nullable<System.DateTime> BITIS_TARIH { get; set; }
    }
}
