//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAHMIN_SONUC
    {
        public int ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public int IDDAA_ID { get; set; }
        public string LIG { get; set; }
        public string TIP { get; set; }
        public string DEGER { get; set; }
        public string POPULER_MAC_MI { get; set; }
        public string OYNANMA_YUZDE_MAX_MI { get; set; }
        public string BOOKMAKER_AZALIYOR_MU { get; set; }
        public string OYNANDI_MI { get; set; }
        public Nullable<decimal> ML_TAHMIN_YUZDE { get; set; }
        public string BOOKMAKER_TAHMIN { get; set; }
    }
}
