//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAHMIN_ML_HEPSI
    {
        public int ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public int IDDAA_ID { get; set; }
        public string LIG { get; set; }
        public string TIP { get; set; }
        public string DEGER { get; set; }
        public decimal IDDAA_ORAN { get; set; }
        public decimal ML_TAHMIN_YUZDE { get; set; }
    }
}
