//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAKIM_ISTATISTIK
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string TAKIM_ADI { get; set; }
        public Nullable<decimal> GOL_DENEMESI { get; set; }
        public Nullable<decimal> SUT_KALEYI_BULAN { get; set; }
        public Nullable<decimal> SUT_KALEYI_BULMAYAN { get; set; }
        public Nullable<decimal> KORNER { get; set; }
        public Nullable<decimal> TOPA_SAHIP_OLMA { get; set; }
        public Nullable<decimal> SUT_ENGELLEME { get; set; }
        public Nullable<decimal> TOPLAM_KART { get; set; }
        public Nullable<decimal> FRIKIK { get; set; }
        public Nullable<decimal> OFSAYT { get; set; }
        public Nullable<decimal> GOL_KAFA { get; set; }
        public Nullable<decimal> GOL_AYAK { get; set; }
        public Nullable<decimal> SARI_KART { get; set; }
        public Nullable<decimal> KIRMIZI_KART { get; set; }
        public Nullable<decimal> ATTIGI_GOL { get; set; }
        public Nullable<decimal> YEDIGI_GOL { get; set; }
        public Nullable<decimal> SUT_ETKISI { get; set; }
        public Nullable<decimal> ATILAN_PENALTI { get; set; }
        public Nullable<decimal> KACAN_PENALTI { get; set; }
        public Nullable<decimal> GOL_YENMEYEN_MAC { get; set; }
    }
}
