//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IddaaWekaTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPLAM_GOL_ISTATISTIK
    {
        public int ID { get; set; }
        public int IDDAA_ID { get; set; }
        public string EV_SAHIBI { get; set; }
        public string DEPLASMAN { get; set; }
        public Nullable<int> GENEL_EV_0_1 { get; set; }
        public Nullable<decimal> GENEL_EV_0_1_ORAN { get; set; }
        public Nullable<int> GENEL_EV_2_3 { get; set; }
        public Nullable<decimal> GENEL_EV_2_3_ORAN { get; set; }
        public Nullable<int> GENEL_EV_4_6 { get; set; }
        public Nullable<decimal> GENEL_EV_4_6_ORAN { get; set; }
        public Nullable<int> GENEL_EV_7_ARTI { get; set; }
        public Nullable<decimal> GENEL_EV_7_ARTI_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_0_1 { get; set; }
        public Nullable<decimal> IC_DIS_EV_0_1_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_2_3 { get; set; }
        public Nullable<decimal> IC_DIS_EV_2_3_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_4_6 { get; set; }
        public Nullable<decimal> IC_DIS_EV_4_6_ORAN { get; set; }
        public Nullable<int> IC_DIS_EV_7_ARTI { get; set; }
        public Nullable<decimal> IC_DIS_EV_7_ARTI_ORAN { get; set; }
        public Nullable<int> ARA_EV_0_1 { get; set; }
        public Nullable<decimal> ARA_EV_0_1_ORAN { get; set; }
        public Nullable<int> ARA_EV_2_3 { get; set; }
        public Nullable<decimal> ARA_EV_2_3_ORAN { get; set; }
        public Nullable<int> ARA_EV_4_6 { get; set; }
        public Nullable<decimal> ARA_EV_4_6_ORAN { get; set; }
        public Nullable<int> ARA_EV_7_ARTI { get; set; }
        public Nullable<decimal> ARA_EV_7_ARTI_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_0_1 { get; set; }
        public Nullable<decimal> GENEL_DEP_0_1_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_2_3 { get; set; }
        public Nullable<decimal> GENEL_DEP_2_3_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_4_6 { get; set; }
        public Nullable<decimal> GENEL_DEP_4_6_ORAN { get; set; }
        public Nullable<int> GENEL_DEP_7_ARTI { get; set; }
        public Nullable<decimal> GENEL_DEP_7_ARTI_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_0_1 { get; set; }
        public Nullable<decimal> IC_DIS_DEP_0_1_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_2_3 { get; set; }
        public Nullable<decimal> IC_DIS_DEP_2_3_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_4_6 { get; set; }
        public Nullable<decimal> IC_DIS_DEP_4_6_ORAN { get; set; }
        public Nullable<int> IC_DIS_DEP_7_ARTI { get; set; }
        public Nullable<decimal> IC_DIS_DEP_7_ARTI_ORAN { get; set; }
        public Nullable<int> ARA_DEP_0_1 { get; set; }
        public Nullable<decimal> ARA_DEP_0_1_ORAN { get; set; }
        public Nullable<int> ARA_DEP_2_3 { get; set; }
        public Nullable<decimal> ARA_DEP_2_3_ORAN { get; set; }
        public Nullable<int> ARA_DEP_4_6 { get; set; }
        public Nullable<decimal> ARA_DEP_4_6_ORAN { get; set; }
        public Nullable<int> ARA_DEP_7_ARTI { get; set; }
        public Nullable<decimal> ARA_DEP_7_ARTI_ORAN { get; set; }
    }
}
